config/routes.rb
Rails.application.routes.draw do
  get 'privacy_policy', controller: :static_pages
  get 'support', controller: :static_pages

  devise_for :admins, path: 'admin', skip: :registrations
  devise_scope :admin do
    authenticated do
      root to: 'admin/room_service/orders#index', as: :authenticated_admin_root
    end

    unauthenticated do
      root to: redirect('admin/sign_in'), as: :unauthenticated_admin_root
    end
  end

  namespace :admin do
    resources :reservations, except: [:show, :destroy]
    resource :reservation_import, only: [:new, :create]

    namespace :room_service do
      resources :orders, only: [:index, :show] do
        member do
          patch :complete
        end
      end
    end
  end

  namespace :api, defaults: { format: :json } do
    namespace :v0 do
      resources :users, only: [:create, :show], module: 'users' do
        resources :reservation_associations, only: [:create]

        namespace :room_service do
          resources :orders, only: [:index, :create]
        end
      end
      resource :authentication, only: [:create, :destroy]

      namespace :room_service do
        resources :categories, only: [:index], module: 'categories' do
          resources :sections, only: [:index]
        end

        resources :items, only: [:show]
      end
    end
  end
end

app/models/reservation.rb
class Reservation < ApplicationRecord
  has_many :user_reservation_associations, class_name: 'User::ReservationAssociation', dependent: :destroy
  has_many :users, through: :user_reservation_associations, inverse_of: :reservations
  has_many :room_service_orders, class_name: 'RoomService::Order', inverse_of: :reservation, dependent: :destroy

  validates_presence_of :confirmation_code, :check_in_date, :check_out_date
  validates_uniqueness_of :confirmation_code, case_sensitive: false
  validates_length_of :confirmation_code, maximum: 30
  validates_length_of :room_number, maximum: 5
  validate :check_out_date_is_not_before_check_in_date

  def includes_today?
    check_in_date <= Date.today && check_out_date >= Date.today
  end

  private

  def check_out_date_is_not_before_check_in_date
    errors.add(:check_out_date, :before_check_in_date, message: "can't be before check-in date") unless
      check_out_date.nil? || check_in_date.nil? || check_in_date <= check_out_date
  end
end

app/models/reservation/opera_arrivals_xml_importer.rb
class Reservation::OperaArrivalsXMLImporter
  RESERVATION_NODE_TITLE = 'G_C6'
  ROOM_NUMBER_NODE_TITLE = 'C9'
  CHECK_IN_DATE_NODE_TITLE = 'C21'
  CHECK_OUT_DATE_NODE_TITLE = 'C24'
  CONFIRMATION_CODE_NODE_TITLE = 'C57'

  def self.xml_string_to_reservations(xml_string)
    doc = Nokogiri::XML(xml_string)

    doc.css(RESERVATION_NODE_TITLE).map do |reservation_element|
      confirmation_code = reservation_element.at_css(CONFIRMATION_CODE_NODE_TITLE).text
      check_in_date_string = reservation_element.at_css(CHECK_IN_DATE_NODE_TITLE).text
      check_out_date_string = reservation_element.at_css(CHECK_OUT_DATE_NODE_TITLE).text
      room_number = reservation_element.at_css(ROOM_NUMBER_NODE_TITLE).text
      room_number = room_number.blank? ? nil : room_number.to_i

      check_in_date = Date.strptime(check_in_date_string, '%d-%b-%y')
      check_out_date = Date.strptime(check_out_date_string, '%d-%b-%y')

      Reservation.new(check_in_date: check_in_date, check_out_date: check_out_date,
                      confirmation_code: confirmation_code, room_number: room_number)
    end
  end
end

app/models/reservation/user_association.rb
class Reservation::UserAssociation < ApplicationRecord
  belongs_to :user
  belongs_to :reservation

  validates_uniqueness_of :reservation, scope: :user_id
end

app/controllers/admin/reservations_controller.rb
class Admin::ReservationsController < AdminController
  def index
    @reservations = Reservation.order(check_in_date: :desc).page params[:page]
  end

  def edit
    @reservation = Reservation.find(params[:id])
  end

  def new
    @reservation = Reservation.new
  end

  def create
    @reservation = Reservation.new(reservation_params)

    if @reservation.save
      flash[:success] = 'Reservation created'

      redirect_to admin_reservations_url
    else
      render :new
    end
  end

  def update
    @reservation = Reservation.find(params[:id])

    if @reservation.update_attributes(reservation_params)
      flash[:success] = 'Reservation updated'

      redirect_to admin_reservations_url
    else
      render :edit
    end
  end

  private

  def load_reservations
    @reservations ||= reservation_scope.to_a
  end

  def reservation_scope
    Reservation.all
  end
end

app/views/admin/reservations/_reservation_form.html.erb
<%= form_for [:admin, @reservation] do |f| %>
    <div class="form-group">
      <%= f.label :check_in_date, 'Check-In Date' %>
      <%= f.text_field :check_in_date, class: 'form-control', data: { provide: 'datepicker', :'date-format' => 'yyyy-mm-dd' } %>
    </div>
    <div class="form-group">
      <%= f.label :check_out_date, 'Check-Out Date' %>
      <%= f.text_field :check_out_date, class: 'form-control', data: { provide: 'datepicker', :'date-format' => 'yyyy-mm-dd' } %>
    </div>
    <div class="form-group">
      <%= f.label :room_number, 'Room Number' %>
      <%= f.text_field :room_number, class: 'form-control' %>
    </div>
    <div class="form-group">
      <%= f.label :confirmation_code, 'Confirmation Code' %>
      <%= f.text_field :confirmation_code, class: 'form-control' %>
    </div>
    <div class="form-group">
      <%= f.label :first_name, 'First Name' %>
      <%= f.text_field :first_name, class: 'form-control' %>
    </div>
    <div class="form-group">
      <%= f.label :last_name, 'Last Name' %>
      <%= f.text_field :last_name, class: 'form-control' %>
    </div>
    <%= submit_tag nil, class: 'btn btn-primary' %>
    <%= link_to 'Cancel', admin_reservations_path, class: 'btn btn-link' %>
<% end %>

app/views/admin/reservations/edit.html.erb
<div class="row">
  <div class="col-md-4 col-md-offset-5">
    <div class="panel panel-primary">
      <div class="panel-heading">
        Edit Reservation
      </div>
      <div class="panel-body">
        <%= render 'reservation_form' %>
      </div>
    </div>
  </div>
</div>

app/views/admin/reservations/index.html.erb
<div class="page-header">
  <h1>Reservations</h1>
  <%= link_to 'New Reservation', new_admin_reservation_path, class: 'btn btn-default' %>
  <%= link_to 'Import Reservations from File', new_admin_reservation_import_path, class: 'btn btn-default' %>
</div>

<table class="table table-striped">
  <thead>
  <tr>
    <th>#</th>
    <th>Check-In Date</th>
    <th>Check-Out Date</th>
    <th>Room Number</th>
    <th>Confirmation Code</th>
    <th>First Name</th>
    <th>Last Name</th>
    <th>Actions</th>
  </tr>
  </thead>
  <tbody>
  <% @reservations.each do |reservation| %>
      <tr data-reservation-id="<%= reservation.id %>">
        <td><%= reservation.id %></td>
        <td><%= reservation.check_in_date.to_s(:long_ordinal) %></td>
        <td><%= reservation.check_out_date.to_s(:long_ordinal) %></td>
        <td><%= reservation.room_number %></td>
        <td><%= reservation.confirmation_code %></td>
        <td><%= reservation.first_name %></td>
        <td><%= reservation.last_name %></td>
        <td><%= link_to 'Edit', edit_admin_reservation_path(reservation) %></td>
      </tr>
  <% end %>
  </tbody>
</table>

<%= paginate @reservations %>

app/views/admin/reservations/new.html.erb
<div class="row">
  <div class="col-md-4 col-md-offset-5">
    <div class="panel panel-primary">
      <div class="panel-heading">
        New Reservation
      </div>
      <div class="panel-body">
        <%= render 'reservation_form' %>
      </div>
    </div>
  </div>
</div>