config/routes.rb
Rails.application.routes.draw do
  get 'privacy_policy', controller: :static_pages
  get 'support', controller: :static_pages

  devise_for :admins, path: 'admin', skip: :registrations
  devise_scope :admin do
    authenticated do
      root to: 'admin/room_service/orders#index', as: :authenticated_admin_root
    end

    unauthenticated do
      root to: redirect('admin/sign_in'), as: :unauthenticated_admin_root
    end
  end

  namespace :admin do
    resources :reservations, except: [:show, :destroy]
    resource :reservation_import, only: [:new, :create]

    namespace :room_service do
      resources :orders, only: [:index, :show] do
        member do
          patch :complete
        end
      end
    end
  end

  namespace :api, defaults: { format: :json } do
    namespace :v0 do
      resources :users, only: [:create, :show], module: 'users' do
        resources :reservation_associations, only: [:create]

        namespace :room_service do
          resources :orders, only: [:index, :create]
        end
      end
      resource :authentication, only: [:create, :destroy]

      namespace :room_service do
        resources :categories, only: [:index], module: 'categories' do
          resources :sections, only: [:index]
        end

        resources :items, only: [:show]
      end
    end
  end
end

app/models/room_service/order.rb
class RoomService::Order < ApplicationRecord
  belongs_to :user, inverse_of: :room_service_orders
  belongs_to :reservation, inverse_of: :room_service_orders, autosave: true
  has_many :cart_items, dependent: :destroy, inverse_of: :order, foreign_key: 'room_service_order_id'

  validate :reservation_belongs_to_user
  validate :reservation_includes_current_day
  validate :reservation_has_room_number_when_setting_status_to_complete
  validates_presence_of :cart_items
  validates_presence_of :payment_type
  validates_presence_of :status

  enum status: [:open, :complete]
  enum payment_type: [:room_account, :cash, :credit_card]

  accepts_nested_attributes_for :cart_items

  def total
    cart_items.map(&:total).reduce(:+)
  end

  private

  def reservation_belongs_to_user
    errors.add(:reservation, :does_not_belong_to_user, message: "doesn't belong to the user") unless
      reservation.nil? || user.nil? || user.reservations.include?(reservation)
  end

  def reservation_includes_current_day
    errors.add(:reservation, :does_not_include_current_day, message: "doesn't include the current day") unless
      reservation.nil? || reservation.includes_today?
  end

  def reservation_has_room_number_when_setting_status_to_complete
    errors.add(:reservation, :does_not_have_room_number, message: "doesn't have a room number") unless
      reservation.nil? || self.open? || reservation.room_number.present?
  end
end

app/controllers/admin/room_service/orders_controller.rb
class Admin::RoomService::OrdersController < AdminController
  def index
    load_orders
  end

  def show
    load_order
  end

  def complete
    load_order
    complete_order or render 'index'
  end

  private

  def load_orders
    @orders ||= order_scope.order(created_at: :desc).page params[:page]
  end

  def load_order
    @order ||= order_scope.find(params[:id])
  end

  def build_order
    @order ||= order_scope.build
    @order.attributes = permitted_attributes(@order)
  end

  def complete_order
    if @order.reservation.room_number.blank? && params[:room_number]
      @order.reservation.room_number = params[:room_number]
    end

    @order.status = 'complete'

    if @order.save
      redirect_to admin_room_service_orders_url
    end
  end

  def order_scope
    RoomService::Order.all
  end
end

app/controllers/api/v0/room_service/orders_controller.rb
class Api::V0::RoomService::OrdersController < Api::V0::ApiController
  def index
    authorize order_scope.build
    load_orders
    render_orders_json or no_content
  end

  def create
    build_order
    authorize @order
    (save_order and send_admin_notification_email) or render_validation_error_json(@order)
  end

  private

  def load_orders
    @orders ||= order_scope.to_a
  end

  def build_order
    @order ||= order_scope.build
    @order.attributes = permitted_attributes(@order)
  end

  def save_order
    response.status = :created unless @order.persisted?
    render_order_json if @order.save
  end

  def render_order_json
    render json: @order,
           include: %w(cart_items cart_items.item cart_items.item.tags cart_items.item.choices cart_items.item.choices.options)
  end

  def render_orders_json
    if @orders.any?
      render json: @orders,
             include: %w(cart_items cart_items.item cart_items.item.tags cart_items.item.choices cart_items.item.choices.options)
    end
  end

  def send_admin_notification_email
    RoomService::OrderMailer.admin_notification(property: current_property, order: @order).deliver_now
  end

  def order_scope
    policy_scope(RoomService::Order).where(user_id: params[:user_id])
  end
end

app/controllers/api/v0/users/room_service/orders_controller.rb
class Api::V0::Users::RoomService::OrdersController < Api::V0::ApiController
  def index
    authorize order_scope.build
    load_orders
    render_orders_json or no_content
  end

  def create
    build_order
    authorize @order
    (save_order and send_admin_notification_email) or render_validation_error_json(@order)
  end

  private

  def load_orders
    @orders ||= order_scope.to_a
  end

  def build_order
    @order ||= order_scope.build
    @order.attributes = permitted_attributes(@order)
  end

  def save_order
    response.status = :created unless @order.persisted?
    render_order_json if @order.save
  end

  def render_order_json
    render json: @order,
           include: %w(cart_items cart_items.item cart_items.item.tags cart_items.item.choices cart_items.item.choices.options)
  end

  def render_orders_json
    if @orders.any?
      render json: @orders,
             include: %w(cart_items cart_items.item cart_items.item.tags cart_items.item.choices cart_items.item.choices.options)
    end
  end

  def send_admin_notification_email
    RoomService::OrderMailer.admin_notification(property: current_property, order: @order).deliver_now
  end

  def order_scope
    RoomService::Order.where(user_id: params[:user_id])
  end
end

app/helpers/room_service/orders_helper.rb
module RoomService::OrdersHelper
  def order_summary(order)
    titles_of_cart_items = order.cart_items.map { |cart_item| cart_item.item.title }.join(', ')

    truncate(titles_of_cart_items, length: 30, omission: '...')
  end

  def order_status_label(order)
    if order.open?
      content_tag(:span, 'Open', class: 'label label-danger')
    else
      content_tag(:span, 'Complete', class: 'label label-success')
    end
  end
end

app/views/admin/orders/index.html.erb
<div class="page-header">
  <h1>Orders</h1>
</div>

<table class="table table-striped">
  <thead>
  <tr>
    <th>Status</th>
    <th>Ordered At</th>
    <th>Summary</th>
    <th>Guest Room Number</th>
    <th>Reservation Confirmation</th>
    <th colspan="2">Actions</th>
  </tr>
  </thead>
  <tbody>
  <% @orders.each do |order| %>
      <tr data-room-service-order-id="<%= order.id %>">
        <td><%= order_status_label(order) %></td>
        <td><%= order.created_at.to_s(:long_ordinal) %></td>
        <td><%= order_summary(order) %></td>
        <td><%= order.reservation.room_number %></td>
        <td><%= order.reservation.confirmation_code %></td>
        <td><%= link_to 'Details', admin_order_path(order), class: 'btn btn-info' %></td>
        <td>
          <%= link_to 'Mark as Complete', complete_admin_order_path(order),
                        method: :put, class: 'btn btn-success',
                        data: { confirm: 'Are you sure you would like to mark this order as complete?' } unless order.completed? %>
        </td>
      </tr>
  <% end %>
  </tbody>
</table>

<%= paginate @orders %>

app/views/admin/orders/room_number_entry.html.erb
<div class="row">
  <div class="col-md-4 col-md-offset-5">
    <div class="panel panel-primary">
      <div class="panel-heading">
        Please enter the room number of the guest.
      </div>
      <div class="panel-body">
        <%= form_tag(complete_admin_order_path, method: :put) do %>
            <div class="form-group">
              <%= label_tag :room_number, 'Room Number' %>
              <%= text_field_tag :room_number, nil, class: 'form-control' %>
            </div>
            <%= submit_tag('Save Room Number', class: 'btn btn-primary') %>
            <%= link_to 'Cancel', admin_orders_path, class: 'btn btn-link' %>
        <% end %>
      </div>
    </div>
  </div>
</div>