config/routes.rb
Rails.application.routes.draw do
  get 'privacy_policy', controller: :static_pages
  get 'support', controller: :static_pages

  devise_for :admins, path: 'admin', skip: :registrations
  devise_scope :admin do
    authenticated do
      root to: 'admin/room_service/orders#index', as: :authenticated_admin_root
    end

    unauthenticated do
      root to: redirect('admin/sign_in'), as: :unauthenticated_admin_root
    end
  end

  namespace :admin do
    resources :reservations, except: [:show, :destroy]
    resource :reservation_import, only: [:new, :create]

    namespace :room_service do
      resources :orders, only: [:index, :show] do
        member do
          patch :complete
        end
      end
    end
  end

  namespace :api, defaults: { format: :json } do
    namespace :v0 do
      resources :users, only: [:create, :show], module: 'users' do
        resources :reservation_associations, only: [:create]

        namespace :room_service do
          resources :orders, only: [:index, :create]
        end
      end
      resource :authentication, only: [:create, :destroy]

      namespace :room_service do
        resources :categories, only: [:index], module: 'categories' do
          resources :sections, only: [:index]
        end

        resources :items, only: [:show]
      end
    end
  end
end

app/models/room_service.rb
module RoomService
  def self.table_name_prefix
    'room_service_'
  end
end

app/models/room_service/cart_item.rb
class RoomService::CartItem < ApplicationRecord
  belongs_to :order, inverse_of: :cart_items, foreign_key: 'room_service_order_id'
  belongs_to :item, foreign_key: 'room_service_item_id'
  has_many :selected_option_associations,
           inverse_of: :cart_item, foreign_key: 'room_service_cart_item_id'
  has_many :selected_options, through: :selected_option_associations

  validates_numericality_of :quantity, greater_than: 0
  validate :item_available
  validate :mandatory_choices_have_selected_options
  validate :single_option_choices_have_single_selection

  def unit_price
    item.price + selected_options.reduce(0) { |sum, option| sum + option.price }
  end

  def total
    unit_price * quantity
  end

  private

  def has_selected_option_for_choice?(choice)
    (choice.option_ids & selected_option_ids).any?
  end

  def has_single_or_no_selected_option_for_choice?(choice)
    (choice.option_ids & selected_option_ids).length <= 1
  end

  def item_available
    errors.add(:item, :not_available_at_the_moment,
               message: '"%{title}" is not available at the moment (only available from %{available_from} to %{available_until})',
               title: item.title,
               available_from: item.available_from.strftime('%H:%M'),
               available_until: item.available_until.strftime('%H:%M'),
               id: item.id) unless item.nil? || item.available_at?(Time.current)
  end

  def mandatory_choices_have_selected_options
    item&.choices&.each do |choice|
      errors.add(:selected_options, :does_not_include_selection_for_mandatory_choice,
                 message: 'should include a selection for "%{choice_title}"',
                 choice_title: choice.title,
                 choice_id: choice.id) unless choice.optional || has_selected_option_for_choice?(choice)
    end
  end

  def single_option_choices_have_single_selection
    item&.choices&.each do |choice|
      errors.add(:selected_options, :includes_multiple_selections_for_single_option_choice,
                 message: 'can only include one selection for "%{choice_title}"',
                 choice_title: choice.title,
                 choice_id: choice.id) unless choice.allows_multiple_options || has_single_or_no_selected_option_for_choice?(choice)
    end
  end
end

app/models/room_service/cart_item/selected_option_association.rb
class RoomService::CartItem::SelectedOptionAssociation < ApplicationRecord
  belongs_to :cart_item, foreign_key: 'room_service_cart_item_id'
  belongs_to :selected_option, foreign_key: 'room_service_item_choice_option_id',
             class_name: 'RoomService::Item::Choice::Option'

  validates_uniqueness_of :selected_option, scope: :room_service_cart_item_id
end

app/models/room_service/category.rb
class RoomService::Category < ApplicationRecord
  DEFAULT_SECTION_TITLE = '__default'

  serialize :available_from, Tod::TimeOfDay
  serialize :available_until, Tod::TimeOfDay

  has_many :sections, foreign_key: 'room_service_category_id',
           dependent: :destroy, inverse_of: :category
  has_attached_file :image, styles: { three_x: '1200x300', two_x: '600x150', one_x: '300x75' }

  validates_presence_of :title
  validates_length_of :title, maximum: 50
  validates_attachment :image, content_type: { content_type: %w(image/jpeg image/png) },
                       size: { in: 0..2.megabytes }

  after_create :create_default_section

  def default_section
    sections.where(title: DEFAULT_SECTION_TITLE).take
  end

  def available_at?(time)
    if available_from.nil? || available_until.nil?
      return true
    end

    available_range = Tod::Shift.new(available_from, available_until)
    available_range.include?(Tod::TimeOfDay(time))
  end

  private

  def create_default_section
    sections.create(title: DEFAULT_SECTION_TITLE)
  end
end

app/models/room_service/category/section.rb
class RoomService::Category::Section < ApplicationRecord
  belongs_to  :category, foreign_key: 'room_service_category_id', inverse_of: :sections
  has_many    :items, foreign_key: 'room_service_category_section_id',
              inverse_of: :category_section, dependent: :destroy

  validates_presence_of :title
  validates_length_of :title, maximum: 50

  delegate :available_at?, to: 'category', allow_nil: true
  delegate :available_from, to: 'category', allow_nil: true
  delegate :available_until, to: 'category', allow_nil: true
  delegate :available_from_local, to: 'category', allow_nil: true
  delegate :available_until_local, to: 'category', allow_nil: true
end

app/models/room_service/item.rb
class RoomService::Item < ApplicationRecord
  belongs_to :category_section, foreign_key: 'room_service_category_section_id',
             counter_cache: 'room_service_items_count', inverse_of: :items, class_name: 'RoomService::Category::Section'
  has_many :item_tag_associations, inverse_of: :item, class_name: 'RoomService::Item::TagAssociation',
           foreign_key: 'room_service_item_id', dependent: :destroy
  has_many :tags, through: :item_tag_associations
  has_many :item_choice_associations, inverse_of: :item, class_name: 'RoomService::Item::ChoiceAssociation',
           foreign_key: 'room_service_item_id', dependent: :destroy
  has_many :choices, through: :item_choice_associations
  has_many :cart_items, inverse_of: :item, class_name: 'RoomService::CartItem',
           foreign_key: 'room_service_item_id', dependent: :destroy

  validates_presence_of :title
  validates_length_of :title, maximum: 50
  validates_length_of :short_description, maximum: 100
  validates_numericality_of :price, greater_than_or_equal_to: 0

  delegate :available_at?, to: :category_section, allow_nil: true
  delegate :available_from, to: :category_section, allow_nil: true
  delegate :available_until, to: :category_section, allow_nil: true
  delegate :available_from_local, to: :category_section, allow_nil: true
  delegate :available_until_local, to: :category_section, allow_nil: true
end

app/models/room_service/item/choice.rb
class RoomService::Item::Choice < ApplicationRecord
  has_many :options, foreign_key: 'room_service_item_choice_id',
           dependent: :destroy, inverse_of: :choice
  belongs_to :default_option,
             class_name: 'RoomService::Item::Choice::Option',
             optional: true
  has_many :item_choice_associations, class_name: 'RoomService::Item::ChoiceAssociation',
           inverse_of: :choice, foreign_key: 'room_service_item_choice_id'
  has_many :items, through: :item_choice_associations

  validates_presence_of :title
  validates_length_of :title, maximum: 50
  validates_length_of :options, minimum: 2
end

app/models/room_service/item/choice/option.rb
class RoomService::Item::Choice::Option < ApplicationRecord
  belongs_to :choice, foreign_key: 'room_service_item_choice_id', inverse_of: :options

  validates_presence_of :title
  validates_length_of :title, maximum: 50
  validates_numericality_of :price, greater_than_or_equal_to: 0
end

app/models/room_service/item/choice_association.rb
class RoomService::Item::ChoiceAssociation < ApplicationRecord
  belongs_to :item, foreign_key: 'room_service_item_id'
  belongs_to :choice, foreign_key: 'room_service_item_choice_id'

  validates_uniqueness_of :choice, scope: :room_service_item_id
end

app/models/room_service/item/tag_association.rb
class RoomService::Item::TagAssociation < ApplicationRecord
  belongs_to :item, foreign_key: 'room_service_item_id'
  belongs_to :tag, foreign_key: 'room_service_tag_id'

  validates_uniqueness_of :tag, scope: :room_service_item_id
end

app/models/room_service/item_choice.rb
class RoomService::ItemChoice < ApplicationRecord
  has_many :options,
           foreign_key: 'room_service_item_choice_id',
           class_name: 'RoomService::ItemChoiceOption',
           dependent: :destroy, inverse_of: :choice
  belongs_to :default_option,
             class_name: 'RoomService::ItemChoiceOption',
             optional: true
  has_many :item_choice_associations, class_name: 'RoomService::Item::ChoiceAssociation',
           inverse_of: :choice, foreign_key: 'room_service_item_choice_id'
  has_many :items, through: :item_choice_associations

  validates_presence_of :title
  validates_length_of :title, maximum: 50
  validates_length_of :options, minimum: 2
end

app/models/room_service/item_choice_option.rb
class RoomService::ItemChoiceOption < ApplicationRecord
  belongs_to :choice, foreign_key: 'room_service_item_choice_id',
             inverse_of: :options, class_name: 'RoomService::Item::Choice'

  validates_presence_of :title
  validates_length_of :title, maximum: 50
  validates_numericality_of :price, greater_than_or_equal_to: 0
end

app/models/room_service/order.rb
class RoomService::Order < ApplicationRecord
  belongs_to :user, inverse_of: :room_service_orders
  belongs_to :reservation, inverse_of: :room_service_orders, autosave: true
  has_many :cart_items, dependent: :destroy, inverse_of: :order, foreign_key: 'room_service_order_id'

  validate :reservation_belongs_to_user
  validate :reservation_includes_current_day
  validate :reservation_has_room_number_when_setting_status_to_complete
  validates_presence_of :cart_items
  validates_presence_of :payment_type
  validates_presence_of :status

  enum status: [:open, :complete]
  enum payment_type: [:room_account, :cash, :credit_card]

  accepts_nested_attributes_for :cart_items

  def total
    cart_items.map(&:total).reduce(:+)
  end

  private

  def reservation_belongs_to_user
    errors.add(:reservation, :does_not_belong_to_user, message: "doesn't belong to the user") unless
      reservation.nil? || user.nil? || user.reservations.include?(reservation)
  end

  def reservation_includes_current_day
    errors.add(:reservation, :does_not_include_current_day, message: "doesn't include the current day") unless
      reservation.nil? || reservation.includes_today?
  end

  def reservation_has_room_number_when_setting_status_to_complete
    errors.add(:reservation, :does_not_have_room_number, message: "doesn't have a room number") unless
      reservation.nil? || self.open? || reservation.room_number.present?
  end
end

app/models/room_service/sub_category.rb
class RoomService::SubCategory < ApplicationRecord
  belongs_to  :category, foreign_key: 'room_service_category_id', inverse_of: :sub_categories
  has_many    :items, foreign_key: 'room_service_sub_category_id', inverse_of: :sub_category, dependent: :destroy

  validates_presence_of :title
  validates_length_of :title, maximum: 50

  delegate :available?, to: 'category', allow_nil: true
  delegate :available_from, to: 'category', allow_nil: true
  delegate :available_until, to: 'category', allow_nil: true
  delegate :available_from_local, to: 'category', allow_nil: true
  delegate :available_until_local, to: 'category', allow_nil: true
end

app/models/room_service/tag.rb
class RoomService::Tag < ApplicationRecord
  has_many :item_tag_associations, class_name: 'RoomService::Item::TagAssociation',
           inverse_of: :tag, foreign_key: 'room_service_tag_id', dependent: :destroy
  has_many :items, through: :item_tag_associations

  validates_presence_of :title
  validates_length_of :title, maximum: 30
end

app/controllers/admin/room_service/orders_controller.rb
class Admin::RoomService::OrdersController < AdminController
  def index
    load_orders
  end

  def show
    load_order
  end

  def complete
    load_order
    complete_order or render 'index'
  end

  private

  def load_orders
    @orders ||= order_scope.order(created_at: :desc).page params[:page]
  end

  def load_order
    @order ||= order_scope.find(params[:id])
  end

  def build_order
    @order ||= order_scope.build
    @order.attributes = permitted_attributes(@order)
  end

  def complete_order
    if @order.reservation.room_number.blank? && params[:room_number]
      @order.reservation.room_number = params[:room_number]
    end

    @order.status = 'complete'

    if @order.save
      redirect_to admin_room_service_orders_url
    end
  end

  def order_scope
    RoomService::Order.all
  end
end

app/controllers/api/v0/room_service/categories/sections_controller.rb
class Api::V0::RoomService::Categories::SectionsController < Api::V0::ApiController
  skip_before_action :authenticate_user_by_auth_token, only: [:index]

  def index
    load_sections
    render_sections or no_content
  end

  private

  def load_sections
    @sections ||= section_scope.to_a
  end

  def render_sections
    render json: @sections, include: :items if @sections.any?
  end

  def section_scope
    ::RoomService::Category::Section
      .where(room_service_category_id: params[:category_id])
      .where('room_service_items_count > 0')
  end
end

app/controllers/api/v0/room_service/categories_controller.rb
class Api::V0::RoomService::CategoriesController < Api::V0::ApiController
  skip_before_action :authenticate_user_by_auth_token, only: [:index]

  def index
    load_categories
    render_categories_json
  end

  private

  def load_categories
    @categories ||= category_scope.to_a
  end

  def render_categories_json
    render json: @categories
  end

  def category_scope
    ::RoomService::Category.all
  end
end

app/controllers/api/v0/room_service/items_controller.rb
class Api::V0::RoomService::ItemsController < Api::V0::ApiController
  skip_before_action :authenticate_user_by_auth_token, only: [:show]

  def show
    load_item
    render_item_json
  end

  private

  def load_item
    @item ||= item_scope.find(params[:id])
  end

  def render_item_json
    render json: @item, include: %w(tags choices choices.options)
  end

  def item_scope
    ::RoomService::Item.all
  end
end

app/controllers/api/v0/room_service/orders_controller.rb
class Api::V0::RoomService::OrdersController < Api::V0::ApiController
  def index
    authorize order_scope.build
    load_orders
    render_orders_json or no_content
  end

  def create
    build_order
    authorize @order
    (save_order and send_admin_notification_email) or render_validation_error_json(@order)
  end

  private

  def load_orders
    @orders ||= order_scope.to_a
  end

  def build_order
    @order ||= order_scope.build
    @order.attributes = permitted_attributes(@order)
  end

  def save_order
    response.status = :created unless @order.persisted?
    render_order_json if @order.save
  end

  def render_order_json
    render json: @order,
           include: %w(cart_items cart_items.item cart_items.item.tags cart_items.item.choices cart_items.item.choices.options)
  end

  def render_orders_json
    if @orders.any?
      render json: @orders,
             include: %w(cart_items cart_items.item cart_items.item.tags cart_items.item.choices cart_items.item.choices.options)
    end
  end

  def send_admin_notification_email
    RoomService::OrderMailer.admin_notification(property: current_property, order: @order).deliver_now
  end

  def order_scope
    policy_scope(RoomService::Order).where(user_id: params[:user_id])
  end
end

app/views/admin/room_service/orders/_room_number_entry_modal.html.erb
<div class="row">
  <div class="col-md-4 col-md-offset-5">
    <div class="panel panel-primary">
      <div class="panel-heading">
        Please enter the room number of the guest.
      </div>
      <div class="panel-body">
        <%= form_for [:admin, @order], url: complete_admin_room_service_order_url(@order) do |f| %>
            <div class="form-group">
              <%= f.fields_for :reservation do |ff| %>
                  <%= ff.label :room_number, 'Room Number' %>
                  <%= ff.text_field :room_number, class: 'form-control' %>
              <% end %>
            </div>
            <%= f.submit 'Save Room Number', class: 'btn btn-primary' %>
            <%= link_to 'Cancel', admin_orders_path, class: 'btn btn-link' %>
        <% end %>
      </div>
    </div>
  </div>
</div>

<div class="modal fade" tabindex="-1" role="dialog">
  <div class="modal-dialog" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
        <h4 class="modal-title">Room number needed</h4>
      </div>
      <div class="modal-body">
        <p>Please enter the room number of the guest.</p>
      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-default" data-dismiss="modal">Cancel</button>
        <button type="button" class="btn btn-primary">Mark as Complete</button>
      </div>
    </div><!-- /.modal-content -->
  </div><!-- /.modal-dialog -->
</div><!-- /.modal -->

app/views/admin/room_service/orders/_selected_options_by_choices.html.erb
<% if selected_options.any? %>
    <ol>
      <% selected_options.group_by { |option| option.choice.title }.each do |choice_title, options| %>
          <li>
            <strong><%= choice_title %>:</strong>
            <% options.each do |option| %>
                <ol>
                  <li><%= option.title %></li>
                </ol>
            <% end %>
          </li>
      <% end %>
    </ol>
<% end %>

app/views/admin/room_service/orders/index.html.erb
<div class="page-header">
  <h1>Orders</h1>
</div>

<table class="table table-striped">
  <thead>
  <tr>
    <th>Status</th>
    <th>Ordered At</th>
    <th>Summary</th>
    <th>Reservation Confirmation</th>
    <th>Room Number</th>
    <th colspan="2">Actions</th>
  </tr>
  </thead>
  <tbody>
  <% @orders.each do |order| %>
      <tr data-room-service-order-id="<%= order.id %>">
        <td><%= order_status_label(order) %></td>
        <td><%= order.created_at.to_s(:long_ordinal) %></td>
        <td><%= order_summary(order) %></td>
        <td><%= order&.reservation.confirmation_code %></td>
        <td><%= order&.reservation.room_number %></td>
        <td>
          <%= link_to 'Details', admin_room_service_order_path(order), class: 'btn btn-info' %>
          <%= link_to 'Mark as Complete', complete_admin_room_service_order_path(order),
                      class: 'btn btn-success', method: :patch,
                      data: { confirm: 'Are you sure you would like to mark this order as complete?' } unless order.complete? %>
        </td>
      </tr>
  <% end %>
  </tbody>
</table>

<%= paginate @orders %>

app/views/admin/room_service/orders/room_number_entry.html.erb
<div class="row">
  <div class="col-md-4 col-md-offset-5">
    <div class="panel panel-primary">
      <div class="panel-heading">
        Please enter the room number of the guest.
      </div>
      <div class="panel-body">
        <%= form_for [:admin, @order], url: complete_admin_room_service_order_url(@order) do |f| %>
            <div class="form-group">
              <%= f.fields_for :reservation do |ff| %>
                  <%= ff.label :room_number, 'Room Number' %>
                  <%= ff.text_field :room_number, class: 'form-control' %>
              <% end %>
            </div>
            <%= f.submit 'Save Room Number', class: 'btn btn-primary' %>
            <%= link_to 'Cancel', admin_orders_path, class: 'btn btn-link' %>
        <% end %>
      </div>
    </div>
  </div>
</div>

app/views/admin/room_service/orders/show.html.erb
<div class="page-header">
  <h1>Order Details</h1>
</div>

<div class="row">
  <div class="col-md-12">
    <table class="table">
      <thead>
      <tr>
        <th>#</th>
        <th>Status</th>
        <th>Ordered At</th>
        <th>Guest Room Number</th>
        <th>Reservation Confirmation</th>
        <th>Total</th>
      </tr>
      </thead>
      <tbody>
      <tr>
        <td><%= @order.id %></td>
        <td><%= order_status_label(@order) %></td>
        <td><%= @order.created_at.to_s(:long_ordinal) %></td>
        <td><%= @order.reservation.room_number %></td>
        <td><%= @order.reservation.confirmation_code %></td>
        <td><%= number_to_currency(@order.total, precision: 3, unit: 'BHD') %></td>
      </tr>
      </tbody>
    </table>
  </div>
</div>

<div class="row">
  <div class="col-md-12">
    <div class="panel panel-primary">
      <div class="panel-heading">
        <h3 class="panel-title">Items</h3>
      </div>
      <div class="panel-body">
        <table class="table table-striped">
          <thead>
          <tr>
            <th>Title</th>
            <th>Quantity</th>
            <th>Selected Options</th>
            <th>Special Request</th>
            <th>Unit Price</th>
            <th>Total</th>
          </tr>
          </thead>
          <tbody>
          <% @order.cart_items.each do |cart_item| %>
              <tr>
                <td><%= cart_item.item.title %></td>
                <td><%= cart_item.quantity %></td>
                <td><%= render 'selected_options_by_choices', selected_options: cart_item.selected_options %></td>
                <td><%= cart_item.special_request %></td>
                <td><%= number_to_currency(cart_item.unit_price, precision: 3, unit: 'BHD') %></td>
                <td><%= number_to_currency(cart_item.total, precision: 3, unit: 'BHD') %></td>
              </tr>
          <% end %>
          </tbody>
        </table>
      </div>
    </div>
  </div>
</div>