config/routes.rb
Rails.application.routes.draw do
  get 'privacy_policy', controller: :static_pages
  get 'support', controller: :static_pages

  devise_for :admins, path: 'admin', skip: :registrations
  devise_scope :admin do
    authenticated do
      root to: 'admin/room_service/orders#index', as: :authenticated_admin_root
    end

    unauthenticated do
      root to: redirect('admin/sign_in'), as: :unauthenticated_admin_root
    end
  end

  namespace :admin do
    resources :reservations, except: [:show, :destroy]
    resource :reservation_import, only: [:new, :create]

    namespace :room_service do
      resources :orders, only: [:index, :show] do
        member do
          patch :complete
        end
      end
    end
  end

  namespace :api, defaults: { format: :json } do
    namespace :v0 do
      resources :users, only: [:create, :show], module: 'users' do
        resources :reservation_associations, only: [:create]

        namespace :room_service do
          resources :orders, only: [:index, :create]
        end
      end
      resource :authentication, only: [:create, :destroy]

      namespace :room_service do
        resources :categories, only: [:index], module: 'categories' do
          resources :sections, only: [:index]
        end

        resources :items, only: [:show]
      end
    end
  end
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Automated Hotel</title>
  <%= csrf_meta_tags %>

  <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
</head>

<body>
<nav class="navbar navbar-default">
  <div class="container-fluid">
    <!-- Brand and toggle get grouped for better mobile display -->
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#main-navbar" aria-expanded="false">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <a class="navbar-brand" href="#">Automated Hotel</a>
    </div>

    <!-- Collect the nav links, forms, and other content for toggling -->
    <div class="collapse navbar-collapse" id="main-navbar">
      <ul class="nav navbar-nav">
        <li><%= link_to 'Orders', admin_room_service_orders_path %></li>
        <li><%= link_to 'Reservations', admin_reservations_path %></li>
      </ul>

      <ul class="nav navbar-nav navbar-right">
        <li><%= link_to 'Sign Out', destroy_admin_session_path, method: :delete %></li>
      </ul>
    </div><!-- /.navbar-collapse -->
  </div><!-- /.container-fluid -->
</nav>

<p class="notice"><%= notice %></p>
<p class="alert"><%= alert %></p>

<div class="container">
  <%= yield %>
</div>
</body>
</html>